using System;
using System.Collections.Generic;
using Microsoft.Win32;

namespace Brisk
{
    // Språklag.
    //
    // Standardspråket er ENGELSK. Kildekoden bruker den norske teksten som nøkkel
    // fordi programmet ble skrevet på norsk først — L.T("Rydding") gir "Cleanup"
    // med mindre brukeren har valgt norsk, og da gis nøkkelen tilbake uendret.
    //
    // tools/sprak_sjekk.py finner nøkler i koden som mangler i tabellen.
    public static class L
    {
        const string SettingsKey = @"Software\Brisk";

        static string lang;

        public static string Lang
        {
            get
            {
                if (lang == null)
                {
                    lang = ReadSetting("Sprak");
                    if (lang != "no") lang = "en";       // engelsk er standard
                }
                return lang;
            }
            set
            {
                lang = (value == "no") ? "no" : "en";
                WriteSetting("Sprak", lang);
            }
        }

        public static bool IsNorwegian { get { return Lang == "no"; } }

        public static string T(string no)
        {
            if (no == null) return null;
            if (Lang == "no") return no;
            string en;
            return Map.TryGetValue(no, out en) && en.Length > 0 ? en : no;
        }

        // Oversetter og setter inn verdier. Nøkkelen bruker {0}, {1} … slik at
        // ordstillingen kan være ulik på de to språkene.
        public static string F(string no, params object[] args)
        {
            try { return string.Format(T(no), args); }
            catch { return T(no); }
        }

        static string ReadSetting(string name)
        {
            try
            {
                using (RegistryKey k = Registry.CurrentUser.OpenSubKey(SettingsKey))
                    return k == null ? null : Convert.ToString(k.GetValue(name));
            }
            catch { return null; }
        }

        static void WriteSetting(string name, string value)
        {
            try
            {
                using (RegistryKey k = Registry.CurrentUser.CreateSubKey(SettingsKey))
                    if (k != null) k.SetValue(name, value);
            }
            catch { }
        }

        // ---------------------------------------------------------------
        // Bygges ved første oppslag. Kan ikke bygges i et felt-initialiserer:
        // statiske felt settes i deklarasjonsrekkefølge, og Pairs står lenger nede.
        static Dictionary<string, string> map;

        static Dictionary<string, string> Map
        {
            get
            {
                if (map == null)
                {
                    Dictionary<string, string> d = new Dictionary<string, string>(StringComparer.Ordinal);
                    for (int i = 0; i + 1 < Pairs.Length; i += 2)
                        d[Pairs[i]] = Pairs[i + 1];
                    map = d;
                }
                return map;
            }
        }

        public static int Count { get { return Map.Count; } }
        public static bool Has(string no) { return Map.ContainsKey(no); }

        // Par: norsk nøkkel, engelsk tekst.
        static readonly string[] Pairs =
        {
            // ---- skall ----
            "Administrator", "Administrator",
            "Begrenset", "Limited",
            "Kjør som administrator", "Run as administrator",
            "Språk", "Language",

            "Oversikt", "Overview",
            // ---- skjermkort og driver ----
            "Skjermdriver", "Graphics driver",
            "Disktemperatur", "Drive temperature",
            "Oppetid", "Uptime",
            "siden forrige omstart", "since the last restart",
            "{0} er ute", "{0} is out",
            "Se etter ny driver", "Check for a new driver",
            "Last ned", "Download",
            "Spør {0} …", "Asking {0} …",
            "Du har nyeste driver ({0}).", "You have the newest driver ({0}).",
            "{0} er ute. Du har {1}.", "{0} is out. You have {1}.",
            "Laster ned {0}-driver {1} …", "Downloading {0} driver {1} …",
            "Lagret som {0}. Brisk starter den ikke — kjør den når du er klar.",
                "Saved as {0}. Brisk does not start it — run it when you are ready.",
            "Windows Update ligger ofte etter for skjermkort. Brisk spør NVIDIA og AMD direkte.",
                "Windows Update is often behind on graphics cards. Brisk asks NVIDIA and AMD directly.",
            "Brisk kan bare sjekke drivere for NVIDIA- og AMD-skjermkort.",
                "Brisk can only check drivers for NVIDIA and AMD graphics cards.",
            "Fant ikke {0} i listene hos NVIDIA.", "Could not find {0} in NVIDIA's lists.",
            "Fant ingen driverversjon på AMD sine sider. De kan ha lagt om.",
                "Found no driver version on AMD's pages. They may have changed the site.",
            "NVIDIA svarte, men uten en driverversjon.", "NVIDIA answered, but without a driver version.",
            "Fikk ikke kontakt med {0}: ", "Could not reach {0}: ",
            "Ingen nedlastingsadresse.", "No download address.",
            "Nedlastingsadressen er ikke fra NVIDIA eller AMD. Avbrutt.",
                "The download address is not from NVIDIA or AMD. Stopped.",
            "Leser skjermkort …", "Reading the graphics card …",
            "Plass", "Space",
            "Ytelse", "Speed",
            "Diagnose", "Diagnostics",
            "Fiks", "Fix",
            // ---- skjerm ----
            "Skjerm", "Screen",
            "Skjermer", "Screens",
            "Oppdateringsfrekvens og farge.", "Refresh rate and colour.",
            "Hovedskjerm", "Main screen",
            "hovedskjerm", "main screen",
            "Fant ingen skjermer", "Found no screens",
            "Skjermene kjører så fort de kan", "Your screens run as fast as they can",
            "Én skjerm kjører saktere enn den kan", "One screen runs slower than it can",
            "{0} skjermer kjører saktere enn de kan", "{0} screens run slower than they can",
            "{0} skjermer kontrollert.", "{0} screens checked.",
            "Du betalte for bildene. Sett dem opp til det panelet klarer.",
                "You paid for the frames. Set them to what the panel can do.",
            "{0} Hz av {1} Hz", "{0} Hz of {1} Hz",
            "{0} Hz — så fort panelet går", "{0} Hz — as fast as the panel goes",
            "Sett til {0} Hz", "Set to {0} Hz",
            "Satt til {0} Hz.", "Set to {0} Hz.",
            "Farge", "Colour",
            "Bruk anbefalt", "Use recommended",
            "Tilbakestill", "Reset",
            "Fargeprofilen er satt.", "The colour profile is set.",
            "Fargen er satt tilbake.", "The colour is back to what it was.",
            "Står som Windows satte den.", "As Windows left it.",
            "står som Windows satte den", "as Windows left it",
            "G-SYNC / FreeSync: {0}–{1} Hz", "G-SYNC / FreeSync: {0}–{1} Hz",
            "Ingen G-SYNC / FreeSync oppgitt", "No G-SYNC / FreeSync reported",
            "Åpner Brisk …", "Opening Brisk …",
            "Beholde denne innstillingen?", "Keep this setting?",
            "Tilbakestilles om {0} sekunder.", "Reverting in {0} seconds.",
            "Frekvensen ble satt tilbake.", "The refresh rate was put back.",
            "{0} kjører nå på {1} Hz. Ser du dette, virker det.",
                "{0} is now running at {1} Hz. If you can read this, it works.",
            "Filen finnes ikke.", "The file is not there.",
            "Filen er ikke signert.", "The file is not signed.",
            "Filen er signert av noen Windows ikke stoler på.",
                "The file is signed by someone Windows does not trust.",
            "Filen er signert, men ikke av utvikleren av Brisk.",
                "The file is signed, but not by the developer of Brisk.",
            "Signaturen er ikke gyldig.", "The signature is not valid.",
            "Signaturen kunne ikke kontrolleres.", "The signature could not be checked.",
            "endret av Brisk", "changed by Brisk",
            "Fargen settes per skjerm. Brisk leser kurven du har nå før den endrer noe, så «Tilbakestill» gir tilbake nøyaktig det den skjermen hadde.",
                "Colour is set per screen. Brisk reads the curve you have now before changing anything, so Reset gives back exactly what that screen had.",
            "Endret av Brisk.", "Changed by Brisk.",
            "metning {0}", "saturation {0}",
            "Dypere svart og litt mer metning. Om det ser bedre ut er en smakssak, så prøv det — Brisk leser kurven du har nå før den endrer noe, så «Tilbakestill» setter tilbake nøyaktig det du hadde.",
                "Deeper blacks and a little more saturation. Whether it looks better is a matter of taste, so try it — Brisk reads the curve you have now before changing anything, so Reset puts back exactly what you had.",
            "Ingen skjerm valgt.", "No screen selected.",
            "Fikk ikke lest gjeldende oppsett.", "Could not read the current setup.",
            "Skjermen støtter ikke denne innstillingen.", "The screen does not support this setting.",
            "Endringen krever omstart.", "The change needs a restart.",
            "Windows avviste endringen.", "Windows rejected the change.",
            "Dette krever administrator.", "This needs administrator.",
            "Windows svarte med kode {0}.", "Windows answered with code {0}.",
            "Windows tok ikke imot fargekurven. Noen skjermkort tillater den ikke.",
                "Windows did not accept the colour curve. Some graphics cards do not allow it.",
            // ---- spill: status og handling ----
            "Optimalisert", "Optimised",
            "Ikke optimalisert", "Not optimised",
            "Optimalisert — krever omstart", "Optimised — restart to apply",
            "Optimaliser", "Optimise",
            "Angre", "Undo",
            "Hent tilbake", "Get it back",
            "Kjører fortsatt", "Still running",
            "Tving av", "Force off",
            "Dette slår av hypervisoren i oppstartskonfigurasjonen.",
                "This turns the hypervisor off in the boot configuration.",
            "Da slutter Hyper-V, WSL2, Docker Desktop, Windows Sandbox og Credential Guard å virke. Bruker du ingen av dem, merker du ingenting utover at spill går fortere.",
                "Hyper-V, WSL2, Docker Desktop, Windows Sandbox and Credential Guard then stop working. If you use none of them, you will notice nothing beyond games running faster.",
            "Endringen gjelder etter omstart, og kan angres her.",
                "The change applies after a restart, and can be undone here.",
            "Slått av. Gjelder etter omstart.", "Turned off. Applies after a restart.",
            "Dette krever administrator. Start Brisk som administrator.",
                "This needs administrator. Start Brisk as administrator.",
            "bcdedit svarte med kode {0}.", "bcdedit answered with code {0}.",
            "gamma {0}", "gamma {0}",
            "kontrast {0}", "contrast {0}",
            "Windows starter den likevel", "Windows starts it anyway",
            "Registeret er satt og maskinen er startet på nytt, men hypervisoren starter likevel.",
                "The registry is set and the machine has restarted, but the hypervisor starts anyway.",
            // ---- NVIDIA-innstillinger ----
            "Strømstyring i driveren", "Driver power management",
            "Shader-buffer", "Shader cache",
            "Lav ventetid", "Low latency",
            "NVIDIA-standard", "NVIDIA default",
            "NVIDIA-driveren tok ikke imot endringen.", "The NVIDIA driver did not accept the change.",
            "Hindrer at skjermkortet klokker ned mellom bildene. Merkes mest på jevnheten.",
                "Stops the graphics card dropping its clock between frames. Most noticeable in how steady it feels.",
            "Litt høyere strømbruk og temperatur når du ikke spiller.",
                "A little more power and heat when you are not playing.",
            "Fjerner hakkingen som kommer når shaders må kompileres om igjen.",
                "Removes the stutter that comes when shaders have to be compiled again.",
            "Bruker mer diskplass.", "Uses more disk space.",
            "Lar driveren ligge mindre på forskudd. Kutter responstiden med omtrent ett bilde.",
                "Lets the driver work less far ahead. Cuts response time by about one frame.",
            "Kan koste et par prosent bilder i bytte mot raskere respons.",
                "May cost a couple of per cent of frames in exchange for faster response.",
            "Xbox Game Bar", "Xbox Game Bar",
            "Installert", "Installed",
            "Avinstallert", "Uninstalled",
            "Overlegget som åpnes med Windows+G. Kjører i bakgrunnen med flere prosesser.",
                "The overlay that opens with Windows+G. Runs in the background across several processes.",
            "Appen avinstalleres. Enkelte Store-spill spør etter den. Kan hentes fra Microsoft Store.",
                "The app is uninstalled. Some Store games ask for it. You can get it back from Microsoft Store.",
            "Windows fjernet den ikke. Prøv å lukke Game Bar først.",
                "Windows did not remove it. Try closing Game Bar first.",
            "Åpner Microsoft Store, der du kan installere den igjen.",
                "Opens Microsoft Store, where you can install it again.",
            "Koster:", "Costs:",
            "Setter innstillingen tilbake slik Windows hadde den.",
                "Puts the setting back the way Windows had it.",
            "Endrer innstillingen slik spill liker den.",
                "Changes the setting to what games prefer.",
            "Se hva hver enkelt koster før du endrer den. To av dem senker sikkerheten.",
                "See what each one costs before you change it. Two of them lower your security.",
            "Bare ting som lar seg måle i bilder per sekund. Triks som «unparking» av kjerner og SystemResponsiveness gjør ingenting, og står derfor ikke her.",
                "Only things that can be measured in frames per second. Tricks like core unparking and SystemResponsiveness do nothing, so they are not here.",
            "Rydding", "Cleanup",
            "Diskplass", "Disk space",
            "Oppstart", "Startup",
            "Minne", "Memory",
            "Oppdateringer", "Updates",
            "Programvare", "Software",
            "Vedlikehold", "Maintenance",
            "Logg", "Log",

            "Tilstanden akkurat nå.", "How things stand right now.",
            "Filer som bare tar plass.", "Files that only take up space.",
            "Hvor plassen har blitt av.", "Where the space went.",
            "Det som starter med Windows.", "What starts with Windows.",
            "Hva RAM-en brukes til.", "What the RAM is used for.",
            "Fra Windows Update.", "Straight from Windows Update.",
            "Oppdater eller fjern programmer.", "Update or remove programs.",
            "Reparasjon og diskhelse.", "Repair and disk health.",
            "Alt som er gjort.", "Everything that has been done.",

            // ---- oversikt ----
            "Ledig på systemdisken", "Free on system drive",
            "Starter med Windows", "Start with Windows",
            "Søppel", "Junk",
            "Kjør sjekk", "Run check",
            "Oppdater", "Refresh",
            "Verdt å se på", "Worth a look",
            "Funn", "Finding",
            "Hva du kan gjøre", "What you can do",
            "Måler søppelfiler og ser etter ting som er verdt å gjøre noe med.",
                "Measures junk files and looks for anything worth acting on.",
            "Måler …", "Measuring …",
            "Avbrutt: ", "Cancelled: ",
            "Ingenting å påpeke.", "Nothing to flag.",
            "Kjør en sjekk for å måle søppelfiler", "Run a check to measure junk files",
            "Bare {0} ledig på {1}", "Only {0} free on {1}",
            "Rydd, eller se hva som tar plassen", "Clean up, or see what's using it",
            "{0} søppelfiler", "{0} of junk files",
            "Rens dem", "Clean them out",
            "{0} programmer starter med Windows", "{0} programs start with Windows",
            "Slå av det du ikke trenger", "Turn off what you don't need",
            "Minnet er {0} % fullt", "Memory is {0}% full",
            "Se hva som bruker det", "See what's using it",
            "{0} enheter melder feil", "{0} devices reporting errors",
            "Se etter drivere", "Look for drivers",
            "Windows.old ligger igjen etter en oppgradering", "Windows.old left over from an upgrade",
            "Kan slettes under Rydding", "Can be deleted under Cleanup",
            "Disken {0} melder «{1}»", "Drive {0} reports \"{1}\"",
            "Ta sikkerhetskopi nå", "Back up now",
            "{0} av {1}", "{0} of {1}",
            "{0} % av {1}", "{0}% of {1}",
            "av {0}", "of {0}",
            "{0} kan ryddes bort.", "{0} can be cleared out.",
            "Kunne ikke lese systemtall: ", "Could not read system figures: ",

            // ---- rydding ----
            "Analyser", "Analyse",
            "Rens", "Clean",
            "Merk alle", "Select all",
            "Kategori", "Category",
            "Størrelse", "Size",
            "Filer", "Files",
            "Merknad", "Note",
            "Les beskrivelsen", "Read the description",
            "Ferdig", "Done",
            "Måler hvor mye hver kategori inneholder. Sletter ingenting.",
                "Measures how much each category holds. Deletes nothing.",
            "{0} kan slettes.", "{0} can be deleted.",
            "Ingenting er merket.", "Nothing is selected.",
            "Sletter {0} kategorier. Dine egne filer, passord og bokmerker røres ikke.",
                "Deleting {0} categories. Your own files, passwords and bookmarks are left alone.",
            "Én av dem er merket med forbehold. Les beskrivelsen først.",
                "One of them is flagged. Read its description first.",
            "Fortsette?", "Continue?",
            "{0} i bruk", "{0} in use",
            "Frigjorde {0}", "Freed {0}",
            "Frigjorde {0}. {1} filer slettet, {2} var i bruk.",
                "Freed {0}. {1} files deleted, {2} were in use.",

            // kategorinavn
            "Midlertidige filer (bruker)", "Temporary files (user)",
            "Midlertidige filer (Windows)", "Temporary files (Windows)",
            "Papirkurv", "Recycle Bin",
            "Windows Update-nedlastinger", "Windows Update downloads",
            "Delivery Optimization", "Delivery Optimization",
            "Krasjdumper", "Crash dumps",
            "Feilrapportering", "Error reporting",
            "Systemlogger", "System logs",
            "Miniatyrbilde- og ikon-cache", "Thumbnail and icon cache",
            "Grafikk-cache", "Graphics cache",
            "Nettleser-cache", "Browser cache",
            "App-cache", "App cache",
            "Windows.old", "Windows.old",
            "Oppsettsrester", "Setup leftovers",

            // kategoribeskrivelser
            "%TEMP%. Rester etter installasjoner og programmer.",
                "%TEMP%. Leftovers from installers and programs.",
            "C:\\Windows\\Temp.", "C:\\Windows\\Temp.",
            "Alle disker.", "All drives.",
            "Ferdig installerte pakker. Lastes ned igjen hvis det trengs.",
                "Already-installed packages. Downloaded again if needed.",
            "Oppdateringer mellomlagret for deling på nettverket.",
                "Updates cached for sharing across the network.",
            "Dumpfiler fra kræsj og blåskjerm.", "Dump files from crashes and blue screens.",
            "Rapporter som lå i kø til Microsoft.", "Reports queued up for Microsoft.",
            "CBS, Windows Update og DISM. Blir fort hundrevis av MB.",
                "CBS, Windows Update and DISM. Easily hundreds of MB.",
            "Bygges opp igjen. Fikser gale miniatyrbilder.",
                "Rebuilt automatically. Fixes wrong thumbnails.",
            "Kompilerte shadere fra DirectX, NVIDIA og AMD. Bygges opp igjen.",
                "Compiled shaders from DirectX, NVIDIA and AMD. Rebuilt automatically.",
            "Bare cache. Passord, bokmerker og innlogginger røres ikke.",
                "Cache only. Passwords, bookmarks and logins are left alone.",
            "Discord, Spotify, Teams, Slack og Office.", "Discord, Spotify, Teams, Slack and Office.",
            "Rester etter oppgradering, ofte 10–30 GB. Sletting fjerner muligheten til å rulle tilbake.",
                "Left over from an upgrade, often 10–30 GB. Deleting it removes the option to roll back.",
            "Panther-logger etter store Windows-oppdateringer.",
                "Panther logs from major Windows updates.",

            // ---- oppstart ----
            "Slå av", "Turn off",
            "Slå på", "Turn on",
            "Planlagte oppgaver", "Scheduled tasks",
            "Navn", "Name",
            "Status", "Status",
            "Utgiver", "Publisher",
            "Hvor", "Where",
            "Kommando", "Command",
            "På", "On",
            "Av", "Off",
            "Behold", "Keep",
            "Reversibelt. Samme mekanisme som Oppgavebehandling — programmet avinstalleres ikke.",
                "Reversible. Same mechanism as Task Manager — nothing gets uninstalled.",
            "{0} oppføringer, {1} på.", "{0} entries, {1} on.",
            "Merk av det du vil endre først.", "Tick what you want to change first.",
            "Disse gjør noe du sannsynligvis vil beholde:", "These do something you probably want to keep:",
            "Slå av likevel?", "Turn off anyway?",
            "Endret {0}.", "Changed {0}.",
            "Endret {0}. {1} feilet — krever administrator.",
                "Changed {0}. {1} failed — administrator required.",
            "Register (denne brukeren)", "Registry (this user)",
            "Register (alle brukere)", "Registry (all users)",
            "Register (32-bit)", "Registry (32-bit)",
            "Oppstartsmappe", "Startup folder",
            "Planlagt oppgave", "Scheduled task",
            "Windows Sikkerhet-ikonet", "Windows Security icon",
            "Lydbehandling (Realtek)", "Audio (Realtek)",
            "Lydbehandling (Waves)", "Audio (Waves)",
            "Lydbehandling (Nahimic)", "Audio (Nahimic)",
            "Styreplate", "Touchpad",
            "Intel-grafikk", "Intel graphics",
            "Hurtigtaster for grafikk", "Graphics hotkeys",
            "NVIDIA-grafikk", "NVIDIA graphics",
            "AMD-grafikk", "AMD graphics",
            "Antivirus", "Antivirus",
            "Skysynkronisering", "Cloud sync",
            "Passordbehandler", "Password manager",

            // ---- minne ----
            "Frigjør arbeidssett", "Trim working sets",
            "Tøm standby-cache", "Purge standby cache",
            "Program", "Program",
            "Minnebruk", "Memory",
            "Prosesser", "Processes",
            "Andel", "Share",
            "Dytter data fra RAM til disk. Tallet faller, men programmene leser det inn igjen. Sjelden noen reell gevinst.",
                "Pushes data from RAM to disk. The number drops, but programs read it straight back. Rarely a real gain.",
            "Sletter Windows sin filcache. Kan hjelpe rett før et stort spill eller en tung render. Ellers gjør den maskinen tregere en stund.",
                "Clears Windows' file cache. Can help right before a big game or a heavy render. Otherwise it makes the machine slower for a while.",
            "Windows bruker ledig RAM som cache med vilje. Vil du ha varig lavere forbruk: kutt oppstartsprogrammer.",
                "Windows uses free RAM as cache on purpose. For lasting lower usage, cut startup programs.",
            "Arbeidssett frigjort.", "Working sets trimmed.",
            "Krever administrator.", "Administrator required.",
            "Tilgjengelig minne endret seg med {0}{1}.", "Available memory changed by {0}{1}.",
            "Klarte ikke tømme standby-cachen.", "Could not purge the standby cache.",
            "av {0}  ·  {1} %", "of {0}  ·  {1}%",
            "Tilgjengelig: {0}", "Available: {0}",
            "Standby-cache: {0}", "Standby cache: {0}",

            // ---- oppdateringer ----
            "Søk", "Search",
            "Installer merkede", "Install selected",
            "Enhetsbehandling", "Device Manager",
            "Spør Windows Update om drivere og systemoppdateringer. Tar gjerne et minutt.",
                "Asks Windows Update for drivers and system updates. Usually takes a minute.",
            "Enheter med problem", "Devices with problems",
            "Enhet", "Device",
            "Problem", "Problem",
            "Enhets-ID", "Device ID",
            "Tilgjengelig fra Microsoft", "Available from Microsoft",
            "Type", "Type",
            "Oppdatering", "Update",
            "Detaljer", "Details",
            "Windows", "Windows",
            "Driver", "Driver",
            "Leser enhetsliste …", "Reading device list …",
            "Spør Windows Update om drivere …", "Asking Windows Update for drivers …",
            "Spør Windows Update om systemoppdateringer …", "Asking Windows Update for system updates …",
            "Ingen enheter med problemer.", "No devices reporting problems.",
            "Alvorlighet: {0}", "Severity: {0}",
            "{0} Windows-oppdateringer og {1} drivere.", "{0} Windows updates and {1} drivers.",
            "Alt er oppdatert.", "Everything is up to date.",
            "Installerer {0} fra Microsoft. Skjermen kan blinke, og noe krever omstart.",
                "Installing {0} from Microsoft. The screen may flicker, and some of it needs a restart.",
            "Installerte {0} av {1}.", "Installed {0} of {1}.",
            "Omstart kreves.", "Restart required.",
            "Omstart", "Restart",
            "Noe av dette krever omstart for å bli aktivt.", "Some of this needs a restart to take effect.",
            "Uten administrator kan du søke, men ikke installere.",
                "Without administrator you can search, but not install.",
            "(ukjent enhet)", "(unknown device)",
            "Enheten er ikke riktig konfigurert", "The device is not configured correctly",
            "Driveren kan være ødelagt, eller systemet er tomt for minne",
                "The driver may be damaged, or the system is out of memory",
            "Enheten kan ikke starte", "The device cannot start",
            "Finner ikke nok ledige ressurser", "Not enough free resources",
            "Krever omstart for å virke", "Needs a restart to work",
            "Driveren må installeres på nytt", "The driver must be reinstalled",
            "Registeret er skadet for denne enheten", "The registry is damaged for this device",
            "Windows fjerner enheten", "Windows is removing the device",
            "Enheten er deaktivert", "The device is disabled",
            "Enheten er ikke til stede eller virker ikke", "The device is absent or not working",
            "Driveren er ikke installert", "No driver is installed",
            "Windows finner ikke driver som virker", "Windows cannot find a working driver",
            "Enheten er ikke koblet til nå", "The device is not connected right now",
            "Feilkode {0}", "Error code {0}",
            "Ingen nye drivere fra Windows Update.", "No new drivers from Windows Update.",
            "Driversøket feilet: ", "Driver search failed: ",
            "Laster ned {0} driver(e).", "Downloading {0} driver(s).",
            "Nedlasting ferdig.", "Download finished.",
            "Ingen drivere ble lastet ned.", "No drivers were downloaded.",
            "Installerer.", "Installing.",
            "Installasjon feilet: ", "Installation failed: ",
            "Windows er oppdatert.", "Windows is up to date.",
            "Oppdateringssøket feilet: ", "Update search failed: ",
            "Laster ned {0} oppdatering(er).", "Downloading {0} update(s).",
            "Ingenting ble lastet ned.", "Nothing was downloaded.",

            // ---- diskplass ----
            "Analyser plass", "Analyse space",
            "Stopp", "Stop",
            "Åpne i Utforsker", "Open in Explorer",
            "Leser gjennom hele treet. Sletter ingenting.", "Walks the whole tree. Deletes nothing.",
            "Dobbeltklikk en rad gjør det samme.", "Double-clicking a row does the same.",
            "Største mapper", "Largest folders",
            "Største filer (over 100 MB)", "Largest files (over 100 MB)",
            "Mappe", "Folder",
            "Fil", "File",
            "Velg en rad først.", "Select a row first.",
            "Kunne ikke åpne: ", "Could not open: ",
            "Går gjennom {0} …", "Walking {0} …",
            "Avbrutt.", "Cancelled.",
            "Avbryter …", "Cancelling …",
            "{0} mapper, {1} store filer", "{0} folders, {1} large files",
            "Ferdig på {0} s. Største post: {1}.", "Done in {0} s. Largest item: {1}.",

            // ---- programvare ----
            "Se etter oppdateringer", "Check for updates",
            "Oppdater merkede", "Update selected",
            "Programoppdateringer (winget)", "Program updates (winget)",
            "Installert", "Installed",
            "Ny versjon", "New version",
            "Pakke-ID", "Package ID",
            "Installerte programmer", "Installed programs",
            "Avinstaller", "Uninstall",
            "Versjon", "Version",
            "winget mangler. Installer «App Installer» fra Microsoft Store.",
                "winget is missing. Install \"App Installer\" from the Microsoft Store.",
            "Spør winget …", "Asking winget …",
            "{0} kan oppdateres.", "{0} can be updated.",
            "Oppdaterte {0} av {1}.", "Updated {0} of {1}.",
            "Velg et program i den nedre lista.", "Select a program in the lower list.",
            "Avinstaller «{0}»? Programmets egen avinstallering starter.",
                "Uninstall \"{0}\"? The program's own uninstaller will start.",
            "Startet avinstallering av {0}.", "Started uninstalling {0}.",
            "Fant ingen avinstalleringskommando for {0}.", "No uninstall command found for {0}.",
            "{0} programmer · {1}", "{0} programs · {1}",
            "Kunne ikke lese programlista: ", "Could not read the program list: ",
            "Fant ingen liste fra winget.", "No list came back from winget.",
            "Klarte ikke tolke winget-utdata.", "Could not parse winget output.",
            "Alt winget kjenner til er oppdatert.", "Everything winget knows about is up to date.",

            // ---- vedlikehold ----
            "Gjenopprettingspunkt", "Restore point",
            "Rydd komponentlager", "Clean component store",
            "Optimaliser disker", "Optimise drives",
            "Tøm DNS-cache", "Flush DNS cache",
            "Planlagt rydding", "Scheduled cleanup",
            "Systemrapport", "System report",
            "Loggmappe", "Log folder",
            "Se etter oppdatering", "Check for update",
            "Automatisk", "Automatic",
            "Lager et tilbakerullingspunkt før du endrer noe.", "Creates a rollback point before you change anything.",
            "Finner og reparerer ødelagte systemfiler. Tar 5–15 minutter.",
                "Finds and repairs damaged system files. Takes 5–15 minutes.",
            "Reparerer kilden sfc henter friske filer fra. Kjør denne først hvis sfc feiler.",
                "Repairs the source sfc pulls clean files from. Run this first if sfc fails.",
            "Fjerner gamle oppdateringsversjoner i WinSxS. Kan ta lang tid og frigjøre flere GB.",
                "Removes superseded update versions in WinSxS. Slow, but can free several GB.",
            "TRIM på SSD, defragmentering på harddisk.", "TRIM on SSDs, defragmentation on hard drives.",
            "Lar Windows kjøre den trygge ryddingen ukentlig av seg selv.",
                "Lets Windows run the safe cleanup weekly on its own.",
            "Lagrer en tekstfil du kan sende til den som hjelper deg.",
                "Saves a text file you can send to whoever is helping you.",
            "Henter versjonsfilen og sjekker nedlastingen mot sha256 før noe kjøres.",
                "Fetches the version file and verifies the download against sha256 before anything runs.",
            "Disk / volum", "Disk / volume",
            "Helse", "Health",
            "Plass", "Space",
            "Volum", "Volume",
            "Frisk", "Healthy",
            "Advarsel", "Warning",
            "Usunn", "Unhealthy",
            "Ukjent", "Unknown",
            "Lite plass", "Low space",
            "{0} ledig av {1}", "{0} free of {1}",
            "Ukentlig rydding er allerede satt opp. Fjerne den?",
                "Weekly cleanup is already set up. Remove it?",
            "Fjernet.", "Removed.",
            "Kjøre den trygge ryddingen hver søndag kl. 12? Windows.old blir aldri tatt.",
                "Run the safe cleanup every Sunday at 12? Windows.old is never touched.",
            "Satt opp: hver søndag kl. 12.", "Set up: every Sunday at 12.",
            "Klarte ikke opprette oppgaven.", "Could not create the task.",
            "Rapport lagret på skrivebordet.", "Report saved to the desktop.",
            "Kunne ikke lagre rapporten: ", "Could not save the report: ",
            "Uten administrator vil de fleste av disse feile.",
                "Without administrator most of these will fail.",
            "Oppretter gjenopprettingspunkt.", "Creating restore point.",
            "Kjører sfc /scannow. Tar 5–15 minutter.", "Running sfc /scannow. Takes 5–15 minutes.",
            "Kjører DISM /RestoreHealth. Kan ta lang tid.", "Running DISM /RestoreHealth. Can take a while.",
            "Rydder komponentlageret (WinSxS).", "Cleaning the component store (WinSxS).",
            "Optimaliserer {0}", "Optimising {0}",
            "Tømmer DNS-cache.", "Flushing DNS cache.",

            // ---- verktøy-sida ----
            "Verktøy", "Tools",
            "Gode gratisverktøy fra andre.", "Good free tools by other people.",
            "MIT", "MIT",
            "Gratis", "Free",
            "Gratis til privat bruk", "Free for personal use",
            "GPLv3", "GPLv3",
            "LGPL", "LGPL",
            "Rydder Windows og fjerner apper du ikke ba om.", "Tweaks Windows and removes apps you never asked for.",
            "Ekstra Windows-verktøy fra Microsoft.", "Extra Windows tools from Microsoft.",
            "Ser hvilken prosess som låser en fil.", "Shows which process is locking a file.",
            "Alt som starter med Windows.", "Everything that starts with Windows.",
            "Diskhelse. Varsler før en disk ryker.", "Drive health. Warns before a disk fails.",
            "Temperaturer, vifter og sensorer.", "Temperatures, fans and sensors.",
            "Slår av sporing og telemetri i Windows.", "Turns off tracking and telemetry in Windows.",
            "Finner filer på navn, med én gang.", "Finds files by name, instantly.",
            "Lager oppstartbar USB fra en ISO.", "Makes a bootable USB from an ISO.",
            "Pakker ut alle arkivformater.", "Extracts every archive format.",

            "Kjør", "Run",
            "Kjører {0} …", "Running {0} …",
            "{0} er ferdig.", "{0} is done.",
            "Avsluttet med kode {0}.", "Exited with code {0}.",
            "Klarte ikke starte {0}: ", "Could not start {0}: ",

            "Konsoll", "Console",
            "Alt verktøyet skriver ut vises her.", "Everything the tool prints appears here.",
            "Ingenting kjører.", "Nothing is running.",
            "Stopper …", "Stopping …",
            "Velg et verktøy over.", "Pick a tool above.",
            "Andres programmer, ikke deler av Brisk. Velg ett, så ser du kommandoen før du kjører den.", "Other people's programs, not parts of Brisk. Pick one and you will see the command before you run it.",
            "Reparasjon", "Repair",
            "Disk og nettverk", "Disk and network",
            "Automatikk og hjelp", "Automation and help",
            "Har aldri sett etter oppdatering.", "Has never checked for an update.",
            "Sist sjekket {0}.", "Last checked {0}.",
            "{0} åpnet i sitt eget vindu.", "{0} opened in its own window.",
            "Ser etter {0} …", "Looking for {0} …",
            "Installerer {0} …", "Installing {0} …",
            "{0} er installert.", "{0} is installed.",
            "{0} er allerede installert.", "{0} is already installed.",
            "Åpnet {0}.", "Opened {0}.",
            "Fant ikke {0} etter installasjonen. Åpne den fra Start-menyen.", "Could not find {0} after installing. Open it from the Start menu.",
            "Allerede installert og oppdatert.", "Already installed and up to date.",
            "Fant ikke pakken. Sjekk ID-en.", "Package not found. Check the ID.",
            "Installasjonen ble avbrutt.", "The install was cancelled.",
            "Ingen kilde svarte. Er du på nett?", "No source responded. Are you online?",
            "{0} åpnet i et eget vindu som administrator.", "{0} opened in its own window as administrator.",
            "Utdata vises i det vinduet, ikke her — start Brisk som administrator hvis du vil ha det her.", "Output appears in that window, not here — start Brisk as administrator if you want it here.",
            "Viser hva slags maskinvare du faktisk har.", "Shows what hardware you actually have.",
            "Eksempel: lister de tyngste prosessene.", "Example: lists the heaviest processes.",
            "Programmet finnes ikke lenger", "The program is no longer installed",
            "Huk av det du vil endre, og trykk «Slå av merkede». Windows måler bare programmer den mener sinker oppstarten merkbart — en strek betyr at den aldri har målt dette.", "Tick what you want to change, then press “Turn off ticked”. Windows only measures programs it thinks noticeably slow startup — a dash means it has never measured this one.",
            "Se hva som kan ryddes", "Review what can be cleaned",
            "Åpner Rydding, der du merker av hva som skal slettes. Ingenting slettes herfra.", "Opens Cleanup, where you tick what to delete. Nothing is deleted from here.",
            // ---- spillmodus ----
            "Spill", "Games",
            "Det som står i veien for bilder per sekund.", "What is standing between you and frames per second.",
            "Spillmodus", "Game mode",
            "Les på nytt", "Read again",
            "Alt står allerede slik spill liker det", "Everything is already set the way games like it",
            "{0} innstillinger kontrollert.", "{0} settings checked.",
            "Én innstilling koster deg bilder", "One setting is costing you frames",
            "{0} innstillinger koster deg bilder", "{0} settings are costing you frames",
            "Les hva hver enkelt koster deg før du slår den av. To av dem senker sikkerheten.", "Read what each one costs you before switching it off. Two of them lower your security.",
            "Endringen gjelder først etter omstart.", "The change takes effect after a restart.",
            "Alt i orden", "Fine as it is",
            "Ikke tilgjengelig", "Not available",
            "Koster deg:", "Costs you:",
            "Sett tilbake", "Put it back",
            "Slå av for spill", "Turn off for games",
            "Merkbar effekt", "Noticeable effect",
            "Liten, men målbar", "Small, but measurable",
            "Varierer mellom spill", "Varies between games",
            "Denne krever administrator. Start Brisk som administrator.", "This one needs administrator. Start Brisk as administrator.",
            "Klarte ikke endre: ", "Could not change it: ",
            "Her står bare ting som lar seg måle i bilder per sekund. Brisk rører ikke tidsoppløsning, «unparking» av kjerner eller SystemResponsiveness — det er triks uten effekt, og de hører ikke hjemme her.", "Only things that can be measured in frames per second are listed here. Brisk does not touch timer resolution, core “unparking” or SystemResponsiveness — those are tricks with no effect, and they do not belong here.",
            "Virtualiseringsbasert sikkerhet", "Virtualisation-based security",
            "Kjører deler av Windows i en virtuell maskin. Koster bilder i alle spill.", "Runs parts of Windows in a virtual machine. Costs frames in every game.",
            "Svakere beskyttelse av innloggingene dine.", "Weaker protection of your sign-ins.",
            "Windows melder ikke om denne på denne maskinen.", "Windows does not report this one on this machine.",
            "Kjører", "Running",
            "På, men kjører ikke", "On, but not running",
            "Minneintegritet", "Memory integrity",
            "Hypervisoren kontrollerer kjernekode. Merkes mest i prosessortunge spill.", "The hypervisor checks kernel code. Most noticeable in processor-heavy games.",
            "Svakere beskyttelse mot ondsinnede drivere.", "Weaker protection against malicious drivers.",
            "Bakgrunnsopptak", "Background recording",
            "Windows spiller inn i bakgrunnen i tilfelle du vil lagre et klipp.", "Windows records in the background in case you want to save a clip.",
            "«Ta opp de siste 30 sekundene» slutter å virke.", "“Record the last 30 seconds” stops working.",
            "Game Bar", "Game Bar",
            "Overlegget som åpnes med Windows+G. Ligger alltid i minnet.", "The overlay that opens with Windows+G. Always sitting in memory.",
            "Snarveier for opptak og skjermbilde slutter å virke.", "Recording and screenshot shortcuts stop working.",
            "Maskinvareakselerert GPU-planlegging", "Hardware-accelerated GPU scheduling",
            "Skjermkortet styrer sin egen minneplanlegging i stedet for Windows.", "The graphics card manages its own memory scheduling instead of Windows.",
            "Effekten varierer. Noen spill vinner, noen taper.", "The effect varies. Some games gain, some lose.",
            "Skjermkortet eller driveren støtter ikke dette.", "The graphics card or its driver does not support this.",
            "Strømplan", "Power plan",
            "Balansert lar prosessoren senke klokken mellom bildene.", "Balanced lets the processor drop its clock between frames.",
            "Mer strøm og varme. På bærbar: kortere batteritid.", "More power and heat. On a laptop: shorter battery life.",
            "Høy ytelse", "High performance",
            "Balansert eller strømsparing", "Balanced or power saver",

            "Denne maskinen", "This machine",
            "Diskslitasje", "Drive wear",
            "ikke lest", "not read",
            "ikke rapportert", "not reported",
            "siste 30 dager", "last 30 days",
            "siste 30 dager · sett", "last 30 days · seen",
            "Merk som sett", "Mark as seen",
            "Blåskjermene blir stående i Windows-loggen, men forsida slutter å påpeke dem.",
                "The blue screens stay in the Windows log, but the front page stops flagging them.",
            "Blåskjermene er merket som sett.", "The blue screens are marked as seen.",
            "ingen dumpfil — kun loggført", "no dump file — only logged",
            "siste 30 dager · fra Windows-loggen", "last 30 days · from the Windows log",
            "Prosessor", "Processor",
            "Skjermkort", "Graphics",
            "Hovedkort", "Motherboard",
            "Oppe siden", "Up for",
            "Minne totalt", "Memory installed",
            // ---- oppstart: flokker og én knapp ----
            "På — {0}", "On — {0}",
            "Av — {0}", "Off — {0}",
            "Slå av {0} merkede", "Turn off {0} selected",
            "Slå på {0} merkede", "Turn on {0} selected",
            "Huk av oppføringer i lista først.", "Tick the entries in the list first.",
            "Lar dem starte med Windows igjen.", "Lets them start with Windows again.",
            "De starter ikke lenger med Windows. Ingenting avinstalleres.",
                "They no longer start with Windows. Nothing is uninstalled.",
            "{0} av dem står allerede av og røres ikke.",
                "{0} of them are already off and are left alone.",
            "{0} av dem står allerede på og røres ikke.",
                "{0} of them are already on and are left alone.",
            "Endret {0}. {1} sto allerede slik.", "Changed {0}. {1} were already that way.",
            "Huk av det du vil endre. Knappen ser selv om de skal slås av eller på. Windows måler bare programmer den mener sinker oppstarten merkbart — en strek betyr at den aldri har målt dette.",
                "Tick what you want to change. The button works out whether to turn them off or on. Windows only measures programs it considers a noticeable delay; a dash means it has never measured this one.",
            "{0} oftest", "{0} most often",
            "{0} % i bruk", "{0} % in use",
            "{0} d", "{0} d",
            "{0} t", "{0} h",
            "{0} min", "{0} min",
            "Fikk ikke kontakt med Windows Update: ", "Could not reach Windows Update: ",
            "Krever administrator. Start Brisk som administrator.", "Needs administrator. Start Brisk as administrator.",
            "Ingenting er merket. Huk av oppdateringene du vil installere først.", "Nothing is ticked. Tick the updates you want to install first.",
            "Installering av oppdateringer krever administrator. Start Brisk som administrator og prøv igjen.", "Installing updates needs administrator. Start Brisk as administrator and try again.",
            "[{0}/{1}] Laster ned: {2}", "[{0}/{1}] Downloading: {2}",
            "[{0}/{1}] Installerer …", "[{0}/{1}] Installing …",
            "[{0}/{1}] Ferdig.", "[{0}/{1}] Done.",
            "[{0}/{1}] Nedlastingen ga ingen fil. Hopper over.", "[{0}/{1}] The download produced no file. Skipping.",
            "[{0}/{1}] Windows avviste den. Kode {2}.", "[{0}/{1}] Windows refused it. Code {2}.",
            "[{0}/{1}] Feilet: {2}", "[{0}/{1}] Failed: {2}",
            "Trykk Søk for å spørre Microsoft om oppdateringer.", "Press Search to ask Microsoft for updates.",
            "Slått av — venter på omstart", "Switched off — waiting for a restart",
            "Starter …", "Starting …",
            "Ser etter søppelfiler …", "Looking for junk files …",
            "Leser oppstartsprogrammer …", "Reading startup programs …",
            "Leser diskhelse …", "Reading drive health …",
            "Leser blåskjermlogg …", "Reading the blue screen log …",
            "Klar.", "Ready.",
            "Se de {0}", "Review the {0}",
            "Dobbeltklikk for å se dem", "Double-click to see them",
            "{0} er huket av", "{0} is ticked",
            // ---- logg ----
            "Åpne loggfil", "Open log file",
            "Tøm visning", "Clear view",

            // ---- oppdatering av programmet ----
            "Ser etter oppdateringer …", "Checking for updates …",
            "Versjon {0} er tilgjengelig.", "Version {0} is available.",
            "Du har nyeste versjon ({0}).", "You have the latest version ({0}).",
            "Kunne ikke vise oppdateringen: ", "Could not show the update: ",
            "Ny versjon tilgjengelig", "Update available",
            "Brisk {0}", "Brisk {0}",
            "Du har {0}", "You have {0}",
            "Ingen endringsbeskrivelse.", "No release notes.",
            "Oppdater nå", "Update now",
            "Ikke nå", "Not now",
            "Lukk", "Close",
            "Laster ned …", "Downloading …",
            "Laster ned … {0} av {1}", "Downloading … {0} of {1}",
            "Nedlastingen feilet.", "The download failed.",
            "Sjekksum bekreftet. Starter installasjonen …", "Checksum verified. Starting the install …",
            "Oppdateringsadressen må være https.", "The update address must be https.",
            "Fikk ikke kontakt med oppdateringskilden: ", "Could not reach the update source: ",
            "Versjonsfilen kunne ikke tolkes.", "The version file could not be parsed.",
            "Nedlastingsadressen i versjonsfilen må være https.",
                "The download address in the version file must be https.",
            "Versjonsfilen mangler en gyldig sha256-sjekksum. Avbryter.",
                "The version file has no valid sha256 checksum. Aborting.",
            "Nedlastingen feilet: ", "The download failed: ",
            "Filen forsvant rett etter nedlastingen. Det er nesten alltid et antivirus som har tatt den.",
                "The file disappeared right after the download. That is almost always an antivirus taking it.",
            "Filen kunne ikke leses etter nedlastingen. Et antivirus har trolig låst den.",
                "The file could not be read after the download. An antivirus has most likely locked it.",
            "Det som ble lastet ned var ikke et program. Noe mellom deg og GitHub byttet ut fila — ofte en antivirus eller et nettverksfilter.",
                "What was downloaded is not a program. Something between you and GitHub replaced the file — often an antivirus or a network filter.",
            "Nedlastingen ble avbrutt underveis. Filen ble slettet — ingenting er kjørt.",
                "The download was cut short. The file was deleted — nothing was run.",
            "Last den ned selv fra utgivelsessida.", "Download it yourself from the releases page.",
            "Åpne nedlastingssida", "Open the download page",
            "Sjekksummen stemte ikke. Filen ble slettet — ingenting er kjørt.",
                "The checksum did not match. The file was deleted — nothing was run.",
            "Klarte ikke starte installasjonen: ", "Could not start the installation: ",

            // ---- feil ----
            "Feil: ", "Error: ",

            // ---- installer ----
            "Installer Brisk", "Install Brisk",
            "Avinstaller Brisk", "Uninstall Brisk",
            "Fjerner programmet og snarveiene fra denne maskinen.",
                "Removes the program and its shortcuts from this machine.",
            "Installer", "Install",
            "Avbryt", "Cancel",
            "Oppdater til {0}", "Update to {0}",
            "Allerede installert.", "Already installed.",
            "Rydder søppelfiler, viser hva som starter med Windows, henter drivere og Windows-oppdateringer fra Microsoft, og finner hvor lagringsplassen har blitt av.",
                "Cleans junk files, shows what starts with Windows, pulls drivers and Windows updates from Microsoft, and finds where your storage went.",
            "Ingen betalingsmur, ingen abonnement, ingen datainnsamling.",
                "No paywall, no subscription, no data collection.",
            "Installeres i:", "Installs to:",
            "Trenger ikke administrator.", "No administrator needed.",
            "Lag snarvei på skrivebordet", "Create a desktop shortcut",
            "Start etter installasjon", "Launch when finished",
            "Dette fjerner programfilene, snarveiene og oppføringen i «Apper og funksjoner». Endringer du har gjort i oppstartsprogrammer beholdes.",
                "This removes the program files, the shortcuts and the entry in Apps & features. Changes you made to startup programs stay as they are.",
            "Installerer …", "Installing …",
            "Avinstallerer …", "Uninstalling …",
            "Det gikk galt", "Something went wrong",
            "Ferdig installert", "Installed",
            "Du finner Brisk i Start-menyen.", "You'll find Brisk in the Start menu.",
            "Brisk er fjernet", "Brisk has been removed",
            "Start Brisk", "Start Brisk",

            // ---- oversikt, ny utgave ----
            "Sjekk PC-en", "Check my PC",
            "Rydd opp", "Clean up",
            "Rydd opp {0}", "Clean up {0}",
            "Alt ser bra ut", "Everything looks fine",
            "Ingenting trenger oppmerksomhet nå.", "Nothing needs your attention.",
            "Kjør en sjekk for å være sikker.", "Run a check to be sure.",
            "Én ting er verdt å se på", "One thing is worth a look",
            "{0} ting er verdt å se på", "{0} things are worth a look",
            "Dobbeltklikk en rad under for å gå dit.", "Double-click a row below to go there.",
            "Ledig plass", "Free space",
            "ikke målt", "not measured",
            "Trykk «Rydd opp»", "Press Clean up",
            "Trykk «Sjekk PC-en» for å måle søppelfiler", "Press Check my PC to measure junk files",
            "Måler søppelfiler og ser etter ting som er verdt å gjøre noe med. Endrer ingenting.",
                "Measures junk files and looks for anything worth acting on. Changes nothing.",
            "Sletter bare det som er merket trygt. Windows.old og dine egne filer røres aldri.",
                "Deletes only what is marked safe. Windows.old and your own files are never touched.",
            "Sletter {0} søppelfiler.", "Deleting {0} of junk files.",
            "Dine egne filer, bilder, passord og bokmerker røres ikke.",
                "Your own files, photos, passwords and bookmarks are left alone.",
            "Begrenset tilgang", "Limited access",
            "Rydding av systemfiler, drivere og reparasjon krever administrator.",
                "Cleaning system files, installing drivers and running repairs need administrator.",
            "{0} blåskjermer siste måned", "{0} blue screens in the last month",
            "Se detaljene under Helse", "See the details under Health",

            // ---- helse ----
            "Helse", "Health",
            "Disker, kræsj og batteri.", "Drives, crashes and battery.",
            "Disker", "Drives",
            "Disk", "Drive",
            "Tilstand", "Condition",
            "Slitasje", "Wear",
            "Temperatur", "Temperature",
            "{0} % brukt", "{0}% used",
            "Blåskjermer", "Blue screens",
            "Når", "When",
            "Stoppkode", "Stop code",
            "Sannsynlig årsak", "Likely cause",
            "Ingen blåskjermer i loggen.", "No blue screens in the log.",
            "Ingen dumpfiler å analysere.", "No dump files to analyse.",
            "Ingen blåskjermer siste 30 dager.", "No blue screens in the last 30 days.",
            "{0} blåskjermer står i Windows-loggen, men dumpfilene er ryddet bort. Uten dem kan ikke Brisk si hvilken driver som feilet.",
                "{0} blue screens are in the Windows log, but the dump files have been cleaned away. Without them Brisk cannot tell you which driver failed.",
            "{0} i loggen uten dumpfil", "{0} in the log with no dump file",
            "Batteri", "Battery",
            "Batteri: {0} % av opprinnelig kapasitet", "Battery: {0}% of its original capacity",
            "Lag rapport", "Save report",
            "Lagrer en tekstfil på skrivebordet du kan sende til den som hjelper deg.",
                "Saves a text file on your desktop you can send to whoever is helping you.",
            "Leser disker …", "Reading drives …",
            "Leser hendelseslogg …", "Reading event log …",

            // stoppkoder
            "Driver rørte minne den ikke skulle", "A driver touched memory it should not have",
            "Feil i minnehåndteringen — test RAM-en", "Memory management fault — test the RAM",
            "Feil i en systemtjeneste", "A system service faulted",
            "Lesing fra ugyldig minne — ofte RAM eller driver",
                "Read from invalid memory — usually RAM or a driver",
            "Driver kræsjet", "A driver crashed",
            "Driver hang under strømsparing", "A driver hung during power saving",
            "En kritisk systemprosess døde", "A critical system process died",
            "Grafikkortet svarte ikke — ofte driver eller varme",
                "The graphics card stopped responding — usually driver or heat",
            "Feil i grafikkdriveren", "Fault in the graphics driver",
            "Maskinvarefeil — CPU, minne eller hovedkort", "Hardware fault — CPU, memory or motherboard",
            "En driver holdt prosessoren for lenge", "A driver held the processor too long",
            "Windows oppdaget minneødeleggelse", "Windows detected memory corruption",
            "Uhåndtert feil i kjernen", "Unhandled fault in the kernel",
            "Driver frigjorde minne feil", "A driver released memory incorrectly",

            // ---- nettverk ----
            "Nettverk", "Network",
            "Er tilkoblingen som den skal?", "Is the connection behaving?",
            "Test tilkoblingen", "Test the connection",
            "Nettverksinnstillinger", "Network settings",
            "Nullstill nettverket", "Reset the network",
            "Test", "Check",
            "Resultat", "Result",
            "Sjekker nettverkskort, gateway, internett, DNS, Wi-Fi, hosts-fil og proxy. Endrer ingenting.",
                "Checks the adapter, gateway, internet, DNS, Wi-Fi, hosts file and proxy. Changes nothing.",
            "Siste utvei når ingenting virker. Nullstiller Winsock og TCP/IP, og krever omstart.",
                "Last resort when nothing works. Resets Winsock and TCP/IP, and needs a restart.",
            "Dette nullstiller nettverksoppsettet og krever omstart. Lagrede Wi-Fi-passord beholdes.",
                "This resets the network configuration and needs a restart. Saved Wi-Fi passwords are kept.",
            "Trykk «Test tilkoblingen» for å komme i gang.", "Press Test the connection to begin.",
            "Alt ser normalt ut.", "Everything looks normal.",
            "{0} problemer funnet.", "{0} problems found.",
            "Nettverkskort", "Adapter",
            "Gateway", "Gateway",
            "Internett", "Internet",
            "DNS", "DNS",
            "Wi-Fi", "Wi-Fi",
            "hosts-fil", "hosts file",
            "Proxy", "Proxy",
            "Ingen aktiv tilkobling", "No active connection",
            "Ingen svar", "No reply",
            "svarer ikke", "no reply",
            "klarte ikke slå opp navn", "could not resolve a name",
            "ukjent", "unknown",
            "Ikke i bruk (kablet)", "Not in use (wired)",
            "Finnes ikke", "Missing",
            "Ren", "Clean",
            "{0} omdirigeringer: ", "{0} redirects: ",
            "Ingen", "None",
            "all trafikk går via denne", "all traffic goes through this",
            "Fornyer IP-adresse.", "Renewing IP address.",
            "Nullstiller Winsock.", "Resetting Winsock.",
            "Nullstiller TCP/IP.", "Resetting TCP/IP.",
            "Ferdig. Start maskinen på nytt for at det skal tre i kraft.",
                "Done. Restart the machine for this to take effect.",

            // ---- oppstartsmåling ----
            "Sinker oppstart", "Delays startup",
            "Oppstart tar {0}", "Startup takes {0}",
            "Forsinkelsen er hentet fra Windows' egen måling av de siste oppstartene.",
                "The delay comes from Windows' own measurement of recent startups.",
            "Windows har ikke logget noen oppstart ennå.", "Windows has not logged a startup yet.",
            "Tjeneste", "Service",
            "Vis logg", "Show log",

            // ---- diskplass, nye moduser ----
            "Største mapper og filer", "Largest folders and files",
            "Duplikater", "Duplicates",
            "Glemte filer", "Forgotten files",
            "Største viser hvor plassen ligger. Duplikater finner like filer. Glemte filer er store filer du ikke har rørt på et halvår.",
                "Largest shows where the space sits. Duplicates finds identical files. Forgotten files are big files you have not touched in six months.",
            "Leser gjennom hele treet. Sletter aldri noe.", "Walks the whole tree. Never deletes anything.",
            "Like filer — behold én, slett resten selv", "Identical files — keep one, delete the rest yourself",
            "Store filer du ikke har rørt på lenge", "Big files you have not touched in a long time",
            "Kopier", "Copies",
            "Kan spares", "Recoverable",
            "{0} kan spares", "{0} recoverable",
            "Sist rørt", "Last touched",
            "{0} dager siden", "{0} days ago",
            "Ingen duplikater funnet. Brukte {0} s.", "No duplicates found. Took {0} s.",
            "{0} grupper med like filer. Brukte {1} s.", "{0} groups of identical files. Took {1} s.",
            "{0} filer, til sammen {1}.", "{0} files, {1} in total.",

            // ---- vedlikehold ----
            "Reparasjon og verktøy.", "Repair and tools.",

            // ---- blåskjermanalyse ----
            "Blåskjermanalyse", "Blue screen analysis",
            "Blåskjermer — dobbeltklikk for full analyse", "Blue screens — double-click for the full analysis",
            "Hva som skjedde", "What happened",
            "Analyserer dumpfiler …", "Analysing dump files …",
            "Åpne analysen", "Open analysis",
            "Leser dumpfila fra kræsjet og viser hvilken driver som feilet.",
                "Reads the crash dump and shows which driver failed.",
            "Ingen dumpfil å analysere.", "No dump file to analyse.",
            "Kunne ikke vise analysen: ", "Could not show the analysis: ",
            "ingen dumpfil", "no dump file",
            "Ukjent stoppkode.", "Unknown stop code.",
            "Fant ingen navngitt modul", "No named module found",
            "Feilen slo ut i {0}", "The fault surfaced in {0}",
            "Sannsynlig årsak: {0}", "Likely cause: {0}",
            "Driver", "Driver",
            "Opphav", "Origin",
            "Rolle", "Role",
            "Sannsynlig årsak", "Likely cause",
            "Feilen slo ut her", "Fault surfaced here",
            "Var involvert", "Was involved",
            "Andre drivere som ikke er fra Windows", "Other drivers that are not from Windows",
            "Kopier oppsummering", "Copy summary",
            "Kopiert", "Copied",
            "Åpne dumpmappa", "Open dump folder",
            "Test minnet", "Test the memory",
            "Windows Minnediagnostikk må starte maskinen på nytt for å teste RAM-en. Lagre arbeidet ditt først.",
                "Windows Memory Diagnostic has to restart the machine to test the RAM. Save your work first.",
            "Åpne den nå?", "Open it now?",
            "ukjent opphav", "unknown origin",
            "Modul", "Module",
            "Parametere", "Parameters",
            "Involvert i kallstakken", "Involved in the call stack",
            "Drivere som ikke er fra Microsoft", "Drivers not from Microsoft",
            "Dumpfilen er for liten til å tolkes.", "The dump file is too small to read.",
            "Ukjent dumpformat ({0}).", "Unknown dump format ({0}).",
            "Klarte ikke lese modullista i dumpen.", "Could not read the module list in the dump.",

            // stoppkoder, forklart
            "En driver leste minne den ikke hadde lov til å røre.",
                "A driver touched memory it was not allowed to.",
            "Windows fant en feil i minnehåndteringen.", "Windows found a fault in memory management.",
            "En driver kastet en feil ingen tok imot.", "A driver raised an error nobody handled.",
            "En systemtjeneste feilet mens den kjørte på vegne av en driver.",
                "A system service faulted while running on behalf of a driver.",
            "Noe skrev i minne som tilhørte kjernen.", "Something wrote into memory belonging to the kernel.",
            "Noe leste fra en minneadresse som ikke fantes.",
                "Something read from a memory address that did not exist.",
            "Maskinvaren meldte en feil den ikke kunne rette.",
                "The hardware reported an error it could not correct.",
            "En driver hang da maskinen skulle sove eller våkne.",
                "A driver hung while the machine was going to sleep or waking up.",
            "En driver ba om minne på feil måte.", "A driver requested memory the wrong way.",
            "Driververifisering fanget en driver som gjorde noe ulovlig.",
                "Driver Verifier caught a driver doing something illegal.",
            "En prosess Windows må ha, døde.", "A process Windows cannot run without died.",
            "En driver skrev utenfor sitt eget område.", "A driver wrote outside its own area.",
            "En prosessorkjerne sluttet å svare.", "A processor core stopped responding.",
            "Grafikkortet sluttet å svare og lot seg ikke nullstille.",
                "The graphics card stopped responding and could not be reset.",
            "En driver holdt prosessoren for lenge uten å gi slipp.",
                "A driver held the processor too long without letting go.",
            "Windows oppdaget at data i kjernen var ødelagt.",
                "Windows detected that kernel data was corrupted.",
            "En vakthund utløste fordi noe hang.", "A watchdog fired because something hung.",

            // raad
            "Dette peker på maskinvare, ikke programvare. Sjekk temperaturer, slå av overklokking, og test minnet.",
                "This points at hardware, not software. Check temperatures, turn off overclocking, and test the memory.",
            "Kjør Windows Minnediagnostikk. Feil i RAM gir ofte akkurat denne.",
                "Run Windows Memory Diagnostic. Faulty RAM often produces exactly this one.",
            "Installer grafikkdriveren på nytt. Er den nettopp oppdatert, prøv forrige versjon.",
                "Reinstall the graphics driver. If it was just updated, try the previous version.",
            "Kjør sfc og DISM under Vedlikehold — systemfiler er sannsynligvis ødelagt.",
                "Run sfc and DISM under Maintenance — system files are probably damaged.",
            "Sannsynlig årsak: {0} fra {1}.", "Likely cause: {0} from {1}.",
            "Oppdater eller avinstaller programvaren {0} hører til. Er den nettopp oppdatert, gå tilbake til forrige versjon.",
                "Update or uninstall the software {0} belongs to. If it was just updated, roll back to the previous version.",
            "Sannsynlig årsak: {0}.", "Likely cause: {0}.",
            "Den fila finnes ikke lenger på maskinen, så driveren er trolig avinstallert eller byttet ut siden kræsjen.",
                "That file is no longer on the machine, so the driver has probably been uninstalled or replaced since the crash.",
            "Feilen skjedde i {0}. Oppdater eller fjern programvaren den hører til.",
                "The fault happened in {0}. Update or remove the software it belongs to.",
            "Feilen slo ut i {0}, som er en del av Windows. Ingen fremmed driver lå i kallstakken.",
                "The fault surfaced in {0}, which is part of Windows. No foreign driver was in the call stack.",
            "Kjør sfc og DISM under Vedlikehold, og se om noen av driverne under er nylig oppdatert.",
                "Run sfc and DISM under Maintenance, and check whether any driver below was recently updated.",
            "Fant ingen navngitt modul på feiladressen. Se hvilke drivere som var involvert nedenfor.",
                "No named module sits at the fault address. See which drivers were involved below.",
            "Oppdater drivere og kjør sfc under Vedlikehold.",
                "Update drivers and run sfc under Maintenance.",

            // ryddekategori
            "Dumpfiler fra kræsj og blåskjerm. Sletter du dem, mister Helse grunnlaget for å analysere blåskjermene dine.",
                "Dump files from crashes and blue screens. Delete them and Health loses what it needs to analyse your blue screens.",

            // ---- plass Windows holder på ----
            "Plass Windows holder på", "Space Windows reserves",
            "Dette er ikke søppel — det er plass Windows har satt av",
                "This is not junk — it is space Windows has set aside",
            "Post", "Item",
            "Hva det er", "What it is",
            "Frigjør plass", "Free it up",
            "Velg en rad for å se hva du kan frigjøre og hva det koster deg.",
                "Select a row to see what you can free and what it costs you.",
            "Denne bør stå i fred. Windows styrer den selv.",
                "Leave this one alone. Windows manages it itself.",
            "Frigjorde {0}.", "Freed {0}.",
            "Ingenting ble frigjort.", "Nothing was freed.",
            "Kunne ikke lese: ", "Could not read: ",

            "Dvalefil", "Hibernation file",
            "Windows reserverer plass lik RAM-en for å kunne dvale. Den brukes også av hurtigoppstart.",
                "Windows reserves space the size of your RAM so it can hibernate. Fast startup uses it too.",
            "Slå av dvale", "Turn off hibernation",
            "Du mister dvalemodus og hurtigoppstart. Maskinen starter fra bunnen hver gang — på en SSD merkes det knapt. Kan slås på igjen når som helst.",
                "You lose hibernation and fast startup. The machine boots from scratch every time — on an SSD you will barely notice. Can be turned back on at any time.",
            "Slår av dvale …", "Turning off hibernation …",
            "Dvalefila er borte.", "The hibernation file is gone.",
            "Fila ligger fortsatt der. Krever administrator.",
                "The file is still there. This needs administrator.",
            "Slår på dvale igjen …", "Turning hibernation back on …",

            "Gjenopprettingspunkter", "Restore points",
            "Eldre kopier av systemfiler og innstillinger, brukt av Systemgjenoppretting.",
                "Older copies of system files and settings, used by System Restore.",
            "Behold bare det nyeste", "Keep only the newest",
            "Du beholder det nyeste punktet og mister de eldre. Du kan fortsatt rulle tilbake, men ikke like langt.",
                "You keep the newest point and lose the older ones. You can still roll back, just not as far.",
            "Fjerner eldre gjenopprettingspunkter …", "Removing older restore points …",

            "Vekslingsfil", "Page file",
            "Windows sitt reservelager når RAM-en tar slutt. Bør stå i fred.",
                "Windows' fallback storage when RAM runs out. Best left alone.",
            "Swapfil for apper", "App swap file",
            "Brukes av Store-apper som settes på pause. Styres av Windows.",
                "Used by Store apps that get suspended. Managed by Windows.",

            // ---- programkræsj ----
            "Programkræsj", "App crashes",
            "Programkræsj siste 30 dager — dobbeltklikk for detaljer",
                "App crashes in the last 30 days — double-click for details",
            "Leser programkræsj …", "Reading app crashes …",
            "Ingen programkræsj siste 30 dager.", "No app crashes in the last 30 days.",
            "Antall", "Count",
            "Sist", "Last",
            "Feilmodul", "Faulting module",
            "Kode", "Code",
            "sluttet å svare", "stopped responding",
            "{0} ganger siste 30 dager, sist {1}.", "{0} times in the last 30 days, most recently {1}.",

            "Leste eller skrev minne den ikke eide", "Read or wrote memory it did not own",
            "Ødela sitt eget minne", "Corrupted its own memory",
            "Skrev utenfor en buffer", "Wrote past the end of a buffer",
            "Feil under håndtering av en annen feil", "Failed while handling another failure",
            "Mistet tilgang til en fil den kjørte fra", "Lost access to a file it was running from",
            "Gikk tom for stakkplass", "Ran out of stack space",
            "Fikk ikke mer minne", "Could not get more memory",
            "Ubehandlet .NET-feil", "Unhandled .NET error",
            "Ubehandlet C++-feil", "Unhandled C++ error",
            "Traff et innebygd stoppunkt", "Hit a built-in breakpoint",
            "Delte på null", "Divided by zero",
            "Prøvde en instruksjon den ikke hadde lov til", "Tried an instruction it was not allowed to run",

            "Programmet sluttet å svare. Skjer det ofte, se om det finnes en nyere versjon.",
                "The program stopped responding. If it happens often, check for a newer version.",
            "Windows fikk ikke tak i hvilken modul som feilet. Oppdater programmet, eller installer det på nytt.",
                "Windows did not capture which module failed. Update the program, or reinstall it.",
            "Programmet feilet i sin egen kode. {0} er bare der Windows fanget feilen. Oppdater eller installer {1} på nytt.",
                "The program failed in its own code. {0} is just where Windows caught it. Update or reinstall {1}.",
            "Feilen ligger i programmet selv ({0}). Oppdater det, eller installer det på nytt.",
                "The fault is in the program itself ({0}). Update it, or reinstall it.",
            "Feilen ligger i {0}, ikke i {1} selv. Oppdater det som eier {0} — ofte en driver eller et tillegg.",
                "The fault is in {0}, not in {1} itself. Update whatever owns {0} — often a driver or an add-on.",

            "Ferdig.", "Done.",
            "{0} — frigjør {1}.", "{0} — frees {1}.",

            // ---- skjermkort og standardvalg ----
            "Av som standard", "Off by default",
            "Fant ingen skjermkort.", "No graphics card found.",
            "Hent hos produsenten", "Get it from the maker",
            "Hent hos {0}", "Get it from {0}",
            "Windows Update ligger ofte etter for skjermkort. Nyeste driver får du hos produsenten.",
                "Windows Update is usually behind on graphics drivers. The newest one comes from the maker.",
            "Åpner produsentens egen nedlastingsside. Aldri en tredjeparts «driver updater».",
                "Opens the maker's own download page. Never a third-party driver updater.",
            "driver", "driver",
            "{0} dager gammel", "{0} days old",
            "Bare mellomlagrede sider og bilder. Historikk, passord, bokmerker, innlogginger og autofyll røres ikke. Av som standard.",
                "Cached pages and images only. History, passwords, bookmarks, logins and autofill are left alone. Off by default.",

            // ---- handlingsfliser og overskrifter ----
            "Kategorier", "Categories",
            "{0} funnet", "{0} found",
            "Velg en kategori for å se nøyaktig hva som slettes.",
                "Select a category to see exactly what gets deleted.",
            "Rens merkede", "Clean selected",
            "Sletter det du har huket av. Analyser først.",
                "Deletes what you have ticked. Analyse first.",
            "Sletter det du har huket av.", "Deletes what you have ticked.",
            "Huker av eller vekk alle kategoriene på én gang.",
                "Ticks or unticks every category at once.",

            "Oppdater listen", "Refresh the list",
            "Leser oppføringene og henter oppstartstidene på nytt.",
                "Reads the entries and the boot timings again.",
            "Slå av merkede", "Turn off selected",
            "Slå på merkede", "Turn on selected",
            "Programmet starter ikke lenger med Windows. Ingenting avinstalleres.",
                "The program stops starting with Windows. Nothing is uninstalled.",
            "Lar det starte med Windows igjen.", "Lets it start with Windows again.",
            "Vis planlagte oppgaver", "Show scheduled tasks",
            "Skjul planlagte oppgaver", "Hide scheduled tasks",
            "Tar med oppgaver som starter ved pålogging, ikke bare vanlige oppstartsprogrammer.",
                "Includes tasks that run at sign-in, not just ordinary startup programs.",
            "Starter med Windows", "Starts with Windows",
            "{0} oppføringer, {1} på", "{0} entries, {1} on",
            "Huk av oppføringene du vil endre først.", "Tick the entries you want to change first.",
            "Huk av det du vil endre, og trykk «Slå av merkede». Tallene kommer fra Windows' egen måling av de siste oppstartene.",
                "Tick what you want to change, then press Turn off selected. The numbers come from Windows' own measurement of recent startups.",

            "Leser minnetallene på nytt.", "Reads the memory figures again.",
            "Hva som bruker minnet", "What is using the memory",
            "{0} programmer", "{0} programs",
            "Dytter data fra RAM til disk. Tallet faller, men programmene leser det inn igjen.",
                "Pushes data from RAM to disk. The number drops, but programs read it straight back.",
            "Sletter Windows sin filcache. Kan hjelpe rett før et stort spill. Ellers gjør den maskinen tregere en stund.",
                "Clears Windows' file cache. Can help right before a big game. Otherwise it makes the machine slower for a while.",

            // ---- vedlikehold ----
            "Sjekk systemfiler", "Check system files",
            "sfc /scannow finner og reparerer ødelagte Windows-filer. Tar 5–15 minutter.",
                "sfc /scannow finds and repairs damaged Windows files. Takes 5–15 minutes.",
            "Reparer Windows-image", "Repair Windows image",
            "DISM reparerer kilden sfc henter friske filer fra. Kjør denne først hvis sfc feiler.",
                "DISM repairs the source sfc pulls clean files from. Run this first if sfc fails.",
            "Lager et punkt du kan rulle tilbake til før du endrer noe.",
                "Creates a point you can roll back to before you change anything.",
            "Hjelper når en nettside peker feil etter en flytting.",
                "Helps when a website points to the wrong place after a move.",
            "Lar Windows kjøre den trygge ryddingen hver uke av seg selv.",
                "Lets Windows run the safe cleanup weekly on its own.",
            "Alt programmet har gjort, med tidspunkt.", "Everything the program has done, with timestamps.",
            "Utdata", "Output",
            "Velg en handling over. Utdataene fra Windows vises her.",
                "Pick an action above. Windows' output appears here.",
            "Kjøre den trygge ryddingen hver søndag kl. 12? Windows.old, krasjdumper og nettleser-cache tas aldri.",
                "Run the safe cleanup every Sunday at 12? Windows.old, crash dumps and browser cache are never touched.",

            // ---- diskplass ----
            "Største", "Largest",
            "Klikk for å velge hvor det skal søkes.", "Click to choose where to search.",
            "Avbryter søket.", "Cancels the search.",
            "Åpner stedet for den valgte raden. Dobbeltklikk gjør det samme.",
                "Opens the location of the selected row. Double-clicking does the same.",
            "Velg en rad først. Du får se hva det koster deg før noe skjer.",
                "Select a row first. You will see what it costs you before anything happens.",
            "Denne raden kan ikke frigjøres.", "This row cannot be freed.",
            "Frigjør {0}.", "Frees {0}.",
            "{0} totalt, {1} kan frigjøres", "{0} in total, {1} can be freed",
            "{0} grupper med like filer. {1} kan spares.", "{0} groups of identical files. {1} recoverable.",

            // ---- programvare ----
            "Spør winget hvilke av programmene dine som har en nyere versjon.",
                "Asks winget which of your programs have a newer version.",
            "Installerer de nye versjonene i bakgrunnen.", "Installs the new versions in the background.",
            "Huker av eller vekk alle oppdateringene.", "Ticks or unticks every update.",
            "Avinstaller valgt", "Uninstall selected",
            "Starter programmets egen avinstallering. Velg i den nedre lista.",
                "Starts the program's own uninstaller. Pick one in the lower list.",
            "{0} kan oppdateres", "{0} can be updated",

            // ---- oppdateringer ----
            "Henter og installerer direkte fra Microsoft. Noe krever omstart.",
                "Downloads and installs straight from Microsoft. Some of it needs a restart.",
            "Åpner Windows sitt eget verktøy for maskinvare.", "Opens Windows' own hardware tool.",
            "Åpner Windows-innstillingene for oppdatering.", "Opens the Windows Update settings.",

            // ---- helse og nettverk ----
            "Leser disker, kræsjlogger og batteri på nytt.",
                "Reads drives, crash logs and battery again.",
            "Leser dumpfila og viser hvilken driver som feilet.",
                "Reads the dump file and shows which driver failed.",
            "Dobbeltklikk en rad for full analyse", "Double-click a row for the full analysis",
            "Siste 30 dager — dobbeltklikk for detaljer", "Last 30 days — double-click for details",
            "{0} dumpfiler analysert", "{0} dump files analysed",
            "Tilkobling", "Connection",
            "Åpner Windows sine egne innstillinger.", "Opens Windows' own settings.",

            "Windows Update", "Windows Update",
        };
    }
}
